# 线上配置文件
#  @author lf
#  
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.236.228:3306/lf
    username: root
    password: 123mysql
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 43.143.236.228
    port: 6379
    timeout: 5000
    password: 123redis
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
